version: '3.8'
services:
  otb_module:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./routes/otb:/home/ubuntu/OTB/routes/otb
      - ./core:/home/ubuntu/OTB/core
      - ./databases:/home/ubuntu/OTB/databases
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DASH_URL=${DASH_URL}
    restart: always

  # sp_cron:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_sp
  #   volumes:
  #     - ./cronjobsp:/etc/cron.d/cronjobsp
  #     - ./core:/home/ubuntu/BMAPS_API/core
  #     - ./databases:/home/ubuntu/BMAPS_API/databases
  #     - ./rapidframes:/home/ubuntu/BMAPS_API/rapidframes
  #     - ./rapidscript:/home/ubuntu/BMAPS_API/rapidscript
  #   environment:
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_URL=${DB_URL}
  #     - DB_PORT=${DB_PORT}
  #     - DB_NAME=${DB_NAME}
  #     - DASH_URL=${DASH_URL}
  #   restart: always


  # db:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_DB=bmaps
  #     - POSTGRES_USER=rebo
  #     - POSTGRES_PASSWORD=password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - bmaps_api_postgres_data:/var/lib/postgresql/data
  #     - ./init.sql:/usr/src/bmaps_api/sql/init.sql
  #   container_name: BMAPS_DB

#   redis:
#     container_name: BMAPS_REDIS_STORE
#     image: redis:latest
#     ports:
#       - "6379:6379"
#     command:
#       - redis-server
#       - --appendonly
#       - yes
#       - --bind
#       - 0.0.0.0
#       - --requirepass
#       - MySecretRedisPassword
#     volumes:
#       - redis-data:/data
#     deploy:
#       resources:
#         limits:
#           cpus: '1.0'
#           memory: 1024M
#     networks:
#       - bmaps_network

#   api:
#     build: .
#     restart: always
#     command: /usr/src/bmaps_api/start.sh
#     depends_on:
#       - db
#       - redis
#     environment:
#       - ALLOW_ORIGIN=http://localhost:8090
#       - REDIS_HOST=redis
#       - REDIS_PASSWORD=MySecretRedisPassword
#       - POSTGRES_HOST=43.204.167.201
#       - POSTGRES_PORT=5432
#       - POSTGRES_DB=bmaps
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=6eA1Wyp6l'sj
#     ports:
#       - "8090:3000"
#     mem_limit: 2G
#     cpu_count: 8
#     container_name: BMAPS_API
#     networks:
#       - bmaps_network

# networks:
#   bmaps_network:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: "49.205.0.0/16"

# volumes:
#   bmaps_api_postgres_data:
#     name: bmaps_api_postgres_data
#   redis-data:
#     name: redis-data
