CREATE  TABLE ra_and_stock_temp
		AS
	SELECT o."ITEMID",
			   o."Description",
			   o."Department",
			   o."Category",
			   o."Family",
			   o."SubFamily",
			   o."SubCategory",
			   o."ExtendedSubCategory",
			   o."SubCategorySupplier",
			   o."AssemblyCodeNickName",
			   -- o."ENDOFLife",
			   o."DOM_COMM",
			   o."Status",
			   o."Supplier",
			   o."Store",
			   o."area",
			   o."Region",
			   o."Company_ABC",
			   o."Family_ABC",
			   o."adjusted_budget_gross_margin_percent",
			   o."budget_amount",
			   o."budget_cost",
			   o."budget_qty",
			   o."Channel",
			   o."INVENTLOCATIONID",
			   o."Budget_date",
			   o."stock_on_hand_qty",
			   o."opening_stock",
			   o."closing_stock",
			   o."current_stock_cost_at_retail",
			   o."stock_received_qty",
			   o."opening_stock_at_cost",
			   o."adjustment_at_cost",
			   o."adjustment_at_retail",
			   o."stock_date",
			   o."article_score_sale",
			   o."article_score_abc",
			   o."article_score_ae",
			   o."article_score_speed",
			   o."article_score_terminal",
			   o."article_score_margin",
			   o."article_score_sell",
			   o."article_score_markdown",
			   o."article_score_core",
			   o."article_score_quartile",
			   o."article_score_sortimeter",
			   o."btech_vs_sortimeter",
			   o."store_sku_count",
			   o."price",
			   stt."LINEAMOUNT",
			   stt."LINEDISC",
			   stt."SALESQTY",
			   stt."COSTPRICE",
			   stt."gross_sales",
			   stt."historical_year",
			   stt."INVOICEDATE",
			   stt."history_quarter",
			   stt."history_month",
			   stt."history_week",
			   stt."history_day"
			   
		FROM temp1 stt  JOIN (SELECT 
								"Channel", "ITEMID", 
								"INVENTLOCATIONID",
							    MAX("Description") AS "Description",
							    MAX("Department") AS "Department",
							    MAX("Category") AS "Category",
							    MAX("Family") AS "Family",
							    MAX("SubFamily") AS "SubFamily",
							    MAX("SubCategory") AS "SubCategory",
							    MAX("ExtendedSubCategory") AS "ExtendedSubCategory",
							    MAX("SubCategorySupplier") AS "SubCategorySupplier",
							    MAX("AssemblyCodeNickName") AS "AssemblyCodeNickName",
							    MAX("DOM_COMM") AS "DOM_COMM",
							    SUM("Status") AS "Status",
							    MAX("Supplier") AS "Supplier",
							    MAX("Company_ABC") AS "Company_ABC",
							    MAX("Family_ABC") AS "Family_ABC",
							    MAX("Store") AS "Store",
							    MAX("area") AS "area",
							    MAX("Region") AS "Region",
							    SUM("adjusted_budget_gross_margin_percent") AS "adjusted_budget_gross_margin_percent",
							    SUM("budget_amount") AS "budget_amount",
							    SUM("budget_cost") AS "budget_cost",
							    SUM("budget_qty") AS "budget_qty",
							    -- MAX("Channel") AS "Channel",
							    -- MAX("INVENTLOCATIONID") AS "INVENTLOCATIONID",
							    MAX("Budget_date") AS "Budget_date",
							    SUM("stock_on_hand_qty") AS "stock_on_hand_qty",
							    SUM("opening_stock") AS "opening_stock",
							    SUM("closing_stock") AS "closing_stock",
							    SUM("current_stock_cost_at_retail") AS "current_stock_cost_at_retail",
							    SUM("stock_received_qty") AS "stock_received_qty",
							    SUM("opening_stock_at_cost") AS "opening_stock_at_cost",
							    SUM("adjustment_at_cost") AS "adjustment_at_cost",
							    SUM("adjustment_at_retail") AS "adjustment_at_retail",
							    MAX("stock_date") AS "stock_date",
							    SUM("article_score_sale") AS "article_score_sale",
							    SUM("article_score_abc") AS "article_score_abc",
							    SUM("article_score_ae") AS "article_score_ae",
							    SUM("article_score_speed") AS "article_score_speed",
							    SUM("article_score_terminal") AS "article_score_terminal",
							    SUM("article_score_margin") AS "article_score_margin",
							    SUM("article_score_sell") AS "article_score_sell",
							    SUM("article_score_markdown") AS "article_score_markdown",
							    SUM("article_score_core") AS "article_score_core",
							    SUM("article_score_quartile") AS "article_score_quartile",
							    SUM("article_score_sortimeter") AS "article_score_sortimeter",
							    SUM("btech_vs_sortimeter") AS "btech_vs_sortimeter",
							    SUM("store_sku_count") AS "store_sku_count",
							    SUM("price") AS "price" 
									from ra_item_stock_kpi_temp group by 
										"Channel", "ITEMID", "INVENTLOCATIONID") o
			
		ON stt."item_code" = o."ITEMID" 
			AND  stt."channel" = o."Channel" 
		AND stt."store_code" = o."INVENTLOCATIONID"

SELECT SUM("LINEAMOUNT") AS L, SUM("budget_amount") as b from ra_and_stock_temp