SELECT o."ITEMID",
			   "Description",
			   "Department",
			   "Category",
			   "Family",
			   "SubFamily",
			   "SubCategory",
			   "ExtendedSubCategory",
			   "SubCategorySupplier",
			   "AssemblyCodeNickName",
			   -- "ENDOFLife",
			   "DOM_COMM",
			   "Status",
			   "Supplier",
			   "Store",
			   "area",
			   "Region",
			   "Company_ABC",
			   "Family_ABC",
			   "adjusted_budget_gross_margin_percent",
			   "budget_amount",
			   "budget_cost",
			   "budget_qty",
			   "Channel",
			   "INVENTLOCATIONID",
			   "Budget_date",
			   "stock_on_hand_qty",
			   "opening_stock",
			   "closing_stock",
			   "current_stock_cost_at_retail",
			   "stock_received_qty",
			   "opening_stock_at_cost",
			   "adjustment_at_cost",
			   "adjustment_at_retail",
			   "stock_date",
			   "article_score_sale",
			   "article_score_abc",
			   "article_score_ae",
			   "article_score_speed",
			   "article_score_terminal",
			   "article_score_margin",
			   "article_score_sell",
			   "article_score_markdown",
			   "article_score_core",
			   "article_score_quartile",
			   "article_score_sortimeter",
			   "btech_vs_sortimeter",
			   "store_sku_count",
			   "price",
			   "LINEAMOUNT",
			   "LINEDISC",
			   "SALESQTY",
			   "COSTPRICE",
			   "gross_sales",
			   "historical_year",
			   "INVOICEDATE",
			   "history_quarter",
			   "history_month",
			   "history_week",
			   "history_day" FROM (
SELECT t1 --*.channel, t1.store_code, t1.item_code, t1.line_amount, o.budget_amount 
 FROM sales_table_temp_ t1 JOIN  (SELECT 
								"Channel", "ITEMID", 
								"INVENTLOCATIONID",
							    MAX("Description") AS "Description",
							    MAX("Department") AS "Department",
							    MAX("Category") AS "Category",
							    MAX("Family") AS "Family",
							    MAX("SubFamily") AS "SubFamily",
							    MAX("SubCategory") AS "SubCategory",
							    MAX("ExtendedSubCategory") AS "ExtendedSubCategory",
							    MAX("SubCategorySupplier") AS "SubCategorySupplier",
							    MAX("AssemblyCodeNickName") AS "AssemblyCodeNickName",
							    MAX("DOM_COMM") AS "DOM_COMM",
							    SUM("Status") AS "Status",
							    MAX("Supplier") AS "Supplier",
							    MAX("Company_ABC") AS "Company_ABC",
							    MAX("Family_ABC") AS "Family_ABC",
							    MAX("Store") AS "Store",
							    MAX("area") AS "area",
							    MAX("Region") AS "Region",
							    SUM("adjusted_budget_gross_margin_percent") AS "adjusted_budget_gross_margin_percent",
							    SUM("budget_amount") AS "budget_amount",
							    SUM("budget_cost") AS "budget_cost",
							    SUM("budget_qty") AS "budget_qty",
							    -- MAX("Channel") AS "Channel",
							    -- MAX("INVENTLOCATIONID") AS "INVENTLOCATIONID",
							    MAX("Budget_date") AS "Budget_date",
							    SUM("stock_on_hand_qty") AS "stock_on_hand_qty",
							    SUM("opening_stock") AS "opening_stock",
							    SUM("closing_stock") AS "closing_stock",
							    SUM("current_stock_cost_at_retail") AS "current_stock_cost_at_retail",
							    SUM("stock_received_qty") AS "stock_received_qty",
							    SUM("opening_stock_at_cost") AS "opening_stock_at_cost",
							    SUM("adjustment_at_cost") AS "adjustment_at_cost",
							    SUM("adjustment_at_retail") AS "adjustment_at_retail",
							    MAX("stock_date") AS "stock_date",
							    SUM("article_score_sale") AS "article_score_sale",
							    SUM("article_score_abc") AS "article_score_abc",
							    SUM("article_score_ae") AS "article_score_ae",
							    SUM("article_score_speed") AS "article_score_speed",
							    SUM("article_score_terminal") AS "article_score_terminal",
							    SUM("article_score_margin") AS "article_score_margin",
							    SUM("article_score_sell") AS "article_score_sell",
							    SUM("article_score_markdown") AS "article_score_markdown",
							    SUM("article_score_core") AS "article_score_core",
							    SUM("article_score_quartile") AS "article_score_quartile",
							    SUM("article_score_sortimeter") AS "article_score_sortimeter",
							    SUM("btech_vs_sortimeter") AS "btech_vs_sortimeter",
							    SUM("store_sku_count") AS "store_sku_count",
							    SUM("price") AS "price" 
									from ra_item_stock_kpi_temp group by 
										"Channel", "ITEMID", "INVENTLOCATIONID") o ON (t1.channel = o."Channel" and 
	t1."INVENTLOCATIONID" = o."INVENTLOCATIONID" and t1."ITEMID" = o."ITEMID") ORDER BY
	t1.channel, t1."INVENTLOCATIONID", t1."ITEMID"
)